In [1]:
import torch
import numpy as np

In [4]:
print(torch.__version__)

1.1.0


In [5]:
np.array([1,2,3])

array([1, 2, 3])

In [6]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
torch.rand(200,200)

tensor([[0.5876, 0.7076, 0.8164,  ..., 0.3499, 0.9700, 0.7362],
        [0.2708, 0.9975, 0.6224,  ..., 0.5791, 0.5116, 0.2897],
        [0.6252, 0.3112, 0.5520,  ..., 0.6774, 0.5797, 0.2899],
        ...,
        [0.4128, 0.7013, 0.5523,  ..., 0.3763, 0.8040, 0.5043],
        [0.9746, 0.8645, 0.3814,  ..., 0.1396, 0.8352, 0.2831],
        [0.1766, 0.0450, 0.6158,  ..., 0.1844, 0.2779, 0.4601]])

In [9]:
torch.rand(3, 200,200)

tensor([[[4.7221e-01, 6.0276e-01, 8.2397e-01,  ..., 5.4681e-04,
          9.3292e-02, 9.2094e-01],
         [9.4484e-01, 4.7779e-01, 2.3122e-01,  ..., 5.7893e-01,
          4.2175e-01, 4.3583e-01],
         [3.2968e-01, 6.3147e-01, 3.4616e-01,  ..., 5.9249e-01,
          8.8917e-01, 5.5168e-01],
         ...,
         [4.8964e-01, 9.0460e-01, 4.3910e-01,  ..., 8.0428e-01,
          5.8596e-01, 2.2763e-01],
         [7.6287e-01, 2.9821e-02, 3.9592e-01,  ..., 9.7596e-01,
          4.0014e-01, 7.7283e-01],
         [6.3397e-01, 8.3694e-01, 3.7866e-01,  ..., 1.8230e-01,
          1.6446e-01, 5.2888e-01]],

        [[1.9865e-02, 7.8617e-01, 8.7021e-01,  ..., 8.4477e-01,
          2.7231e-01, 1.3252e-01],
         [8.2943e-01, 3.8967e-01, 7.7170e-01,  ..., 1.1205e-01,
          6.2277e-01, 9.2684e-02],
         [5.7125e-01, 3.2246e-01, 6.3755e-01,  ..., 3.7293e-02,
          7.1368e-01, 2.8944e-01],
         ...,
         [8.1897e-01, 6.9362e-01, 9.9920e-01,  ..., 6.9764e-01,
          8.211

In [12]:
import autograd.numpy as np
# autograd allow automatic differentation on numpy arrays

In [2]:
# i.e. video data batch_sze, timestemps, channel, image size, image size
x = torch.rand(100, 100, 3, 200,200)

In [3]:
x_numpy = np.array([1,2,3,4])
torch.from_numpy(x_numpy)

tensor([1, 2, 3, 4])

In [6]:
x_cuda = x.cuda()

In [7]:
x.device

device(type='cpu')

In [8]:
x_cuda.device

device(type='cuda', index=0)

from torch.autograd import Variable is not longer needed

In [24]:
def f(a, b):
    c = a * b
    d= torch.log(c)
    return d

In [25]:
a = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

In [20]:
x.shape

torch.Size([])

In [26]:
y = f(a,b)
print(y)

tensor(1.7918, grad_fn=<LogBackward>)


In [27]:
y.backward()
print(a.grad, b.grad)

tensor(0.5000) tensor(0.3333)
